on: [push]

jobs:
  sylius_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      -
          name: Hello world action step
          uses: ferror/sylius-github-action@v4
      -
        name: create sylius project
        run: |
            composer create-project sylius/sylius-standard app
